apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap-stage
data:
  USER: root
  PASSWORD: root
  DATABASE_URL: mysql://10.30.72.217:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
  
  
  # DATABASE_URL: mysql://10.111.41.255:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC # caso esteja vinculando um clusterIP na mão
        